# Generated by Django 5.1.2 on 2024-11-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applying_to", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("date_of_birth", models.CharField(max_length=6)),
                ("phone_num", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("residence", models.CharField(max_length=100)),
                ("educational_background", models.CharField(max_length=50)),
                ("school", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("certificate", models.CharField(max_length=200)),
                ("it_experience", models.CharField(max_length=200)),
                ("education_experience", models.CharField(max_length=50)),
                ("it_career_experience", models.CharField(max_length=50)),
                ("card_possession", models.CharField(max_length=100)),
                ("motivation_career_plan", models.TextField()),
                ("source_of_info", models.CharField(max_length=100)),
            ],
        ),
    ]
